encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.page, name="page"),
    path("create", views.new_page, name="new_page"),
    path("edit/<str:title>", views.edit_page, name="edit_page"),
    path("random", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from markdown2 import Markdown
from . import util
markdowner = Markdown()

def index(request):
    entries = util.list_entries()
    title_list = []
    if request.method == 'POST':
        title = request.POST['title']
        for entry in entries:
            if title.lower() == entry.lower():
                return HttpResponseRedirect(reverse('encyclopedia:page', args=[title]))

        for entry in entries:
            if title.lower() in entry.lower():
                title_list.append(entry)

        if len(title_list) == 0:
            return render(request, 'encyclopedia/error.html')
        return render(request, 'encyclopedia/search_results.html', {'title_list': title_list})
    return render(request, 'encyclopedia/index.html', {
        'entries': entries
    })


def page(request, title):
    entry = util.get_entry(title)
    if entry:
        return render(request, 'encyclopedia/page.html', {'title':title,
            'magic':markdowner.convert(entry)
        })
    else:
        return render(request, 'encyclopedia/error.html')


def new_page(request):
    if request.method == 'POST':
        entries = util.list_entries()
        title = request.POST['title']
        for entry in entries:
            if title.lower() == entry.lower():
                messages.warning(request, 'Similar page already exists')
                return HttpResponseRedirect(reverse('encyclopedia:new_page'))

        content = request.POST['content']
        util.save_entry(title, content)
        messages.success(request, 'Page added')
        return render(request, 'encyclopedia/new_page.html', {
            'title': title
        })
    return render(request, 'encyclopedia/new_page.html')


def edit_page(request, title):
    if request.method == 'POST':
        content = request.POST['content']
        util.save_entry(title, content)
        messages.success(request, 'Page modified.')
        return HttpResponseRedirect(reverse('encyclopedia:page', args=[title]))
    entry = util.get_entry(title)
    if entry:
        return render(request, 'encyclopedia/edit_page.html', {
            'title':title,
            'entry':entry
        })
    return render(request, 'encyclopedia/error.html')


def random_page(request):
    entries = util.list_entries()
    title = random.choice(entries)
    return HttpResponseRedirect(reverse('encyclopedia:page', args=[title]))

encyclopedia/templates/encyclopedia/edit_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Encyclopedia</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
  <style>
    html, body {
    max-width: 100%;
    overflow-x: hidden;
    }
    .alert {
      width: 80vw !important;
    }
    #exampleFormControlInput1 {
      width: 30vw !important;
    }
    textarea {
      height: 50vh !important;
      width: 80vw !important;
    }
  </style>
</head>
<body>
  <div class="row">
    <div class="sidebar col-lg-2 col-md-3">
        <h2>Wiki</h2>
        <form action="{% url 'encyclopedia:index' %}" method="POST">
            {% csrf_token %}
            <input class="search" name="title" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
            <button type="submit" class="btn btn-info btn-sm mt-2">Submit</button>
        </form>
        <div>
            <a href="{% url 'encyclopedia:index' %}">Home</a>
        </div>
        <div>
            <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
        </div>
        <div>
            <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
        </div>
    </div>
    <div class="main col-lg-10 col-md-9">
      <!-- {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              <strong>Success!</strong> {{ message }} <a href="{% url 'encyclopedia:page' title %}">View</a>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %} -->
      <h1>Edit page</h1>
      <form action="{% url 'encyclopedia:edit_page' title %}" method="POST">
        {% csrf_token %}
        <fieldset disabled>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Title</label>
                <input type="text" name="title" class="form-control" id="exampleFormControlInput1" placeholder="Title" value="{{ title }}">
                <div id="passwordHelpBlock" class="form-text">
                    Title cannot be editted.
                </div>
            </div>
        </fieldset>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Content</label>
            <textarea name="content" id="exampleFormControlTextarea1" class="form-control">{{ entry }}</textarea>
        </div>
        <button type="submit" class="btn btn-danger">Save</button>
      </form>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>404 Page not found.</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <script src="https://kit.fontawesome.com/0ebed21091.js" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" name="title" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
                    <button type="submit" class="btn btn-info btn-sm mt-2">Submit</button>
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Encyclopedia</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
  <style>
    html, body {
    max-width: 100%;
    overflow-x: hidden;
    }
    .alert {
      width: 80vw !important;
    }
    #exampleFormControlInput1 {
      width: 30vw !important;
    }
    textarea {
      height: 50vh !important;
      width: 80vw !important;
    }
  </style>
</head>
<body>
  <div class="row">
    <div class="sidebar col-lg-2 col-md-3">
        <h2>Wiki</h2>
        <form action="{% url 'encyclopedia:index' %}" method="POST">
            {% csrf_token %}
            <input class="search" name="title" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
            <button type="submit" class="btn btn-info btn-sm mt-2">Submit</button>
        </form>
        <div>
            <a href="{% url 'encyclopedia:index' %}">Home</a>
        </div>
        <div>
            <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
        </div>
        <div>
            <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
        </div>
    </div>
    <div class="main col-lg-10 col-md-9">
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == "warning" %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <strong>Oops!</strong> {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% else %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              <strong>Success!</strong> {{ message }} <a href="{% url 'encyclopedia:page' title %}">View</a>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      <h1>Add Page</h1>
      <form action="{% url 'encyclopedia:new_page' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Title</label>
            <input type="text" name="title" class="form-control" id="exampleFormControlInput1" placeholder="Title">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Content</label>
            <textarea name="content" id="exampleFormControlTextarea1" class="form-control"></textarea>
          </div>
          <button type="submit" class="btn btn-dark">Submit</button>
      </form>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Success!</strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    {% endif %}
    {{ magic|safe }}
    <a href="{% url 'encyclopedia:edit_page' title %}" class="btn btn-warning" role="button">Edit</a>
    
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Did you mean? </h1>
    <ul>
        {% for title in title_list %}
            <li><a href="{% url 'encyclopedia:page' title %}">{{ title }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}